<?php

namespace Fintech\Banco\Seeders;

use Fintech\Banco\Facades\Banco;
use Illuminate\Database\Seeder;

class BankSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        foreach ($this->data() as $bank) {
            if ($bank['logo_png'] != null) {
                $image_png = __DIR__ . '/../../resources/img/bank_logo_png/' . $bank['logo_png'];
                $bank['logo_png'] = 'data:image/png;base64,' . base64_encode(file_get_contents($image_png));
            }
            if ($bank['logo_svg'] != null) {
                $image_svg = __DIR__ . '/../../resources/img/bank_logo_svg/' . $bank['logo_svg'];
                $bank['logo_svg'] = 'data:image/svg+xml;base64,' . base64_encode(file_get_contents($image_svg));
            }
            Banco::bank()->create($bank);
        }
    }

    private function data()
    {
        return array(
            array(
                'id' => '1',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'AGRANI BANK LIMITED',
                'category' => 'State-owned Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_3.png',
                'logo_svg' => 'bank_logo_3.svg',
            ),
            array(
                'id' => '2',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'AL-ARAFAH ISLAMI BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_24.png',
                'logo_svg' => 'bank_logo_24.svg',
            ),
            array(
                'id' => '3',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'AB BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_35.png',
                'logo_svg' => 'bank_logo_35.svg',
            ),
            array(
                'id' => '4',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'BANGLADESH BANK',
                'category' => 'Central Bank',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_1.png',
                'logo_svg' => 'bank_logo_1.svg',
            ),
            array(
                'id' => '5',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'BANGLADESH COMMERCE BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_30.png',
                'logo_svg' => 'bank_logo_30.svg',
            ),
            array(
                'id' => '6',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'BANGLADESH KRISHI BANK',
                'category' => 'Specialized Development',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_38.png',
                'logo_svg' => 'bank_logo_38.svg',
            ),
            array(
                'id' => '7',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'BANGLADESH SAMABAYA BANK LIMITED',
                'category' => 'Specialized Development',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_42.png',
                'logo_svg' => 'bank_logo_42.svg',
            ),
            array(
                'id' => '8',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'BANGLADESH DEVELOPMENT BANK LIMITED',
                'category' => 'Specialized Development',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_41.png',
                'logo_svg' => 'bank_logo_41.svg',
            ),
            array(
                'id' => '9',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'BASIC BANK LIMITED',
                'category' => 'Specialized Development',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_44.png',
                'logo_svg' => 'bank_logo_44.svg',
            ),
            array(
                'id' => '10',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'BRAC BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_6.png',
                'logo_svg' => 'bank_logo_6.svg',
            ),
            array(
                'id' => '11',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'BANK AL-FALAH LIMITED',
                'category' => 'Foreign Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_53.png',
                'logo_svg' => 'bank_logo_53.svg',
            ),
            array(
                'id' => '12',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'BANK ASIA LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_28.png',
                'logo_svg' => 'bank_logo_28.svg',
            ),
            array(
                'id' => '13',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'CITI BANK N A',
                'category' => 'Foreign Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_47.png',
                'logo_svg' => 'bank_logo_47.svg',
            ),
            array(
                'id' => '14',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'COMMERCIAL BANK OF CYLON',
                'category' => NULL,
                'transaction_type' => NULL,
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_50.png',
                'logo_svg' => 'bank_logo_50.svg',
            ),
            array(
                'id' => '15',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'DHAKA BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_11.png',
                'logo_svg' => 'bank_logo_11.svg',
            ),
            array(
                'id' => '16',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'DUTCH-BANGLA BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_7.png',
                'logo_svg' => 'bank_logo_7.svg',
            ),
            array(
                'id' => '17',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'EASTERN BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_8.png',
                'logo_svg' => 'bank_logo_8.svg',
            ),
            array(
                'id' => '18',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'EXIM BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_26.png',
                'logo_svg' => 'bank_logo_26.svg',
            ),
            array(
                'id' => '19',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'FIRST SECURITY ISLAMI BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_27.png',
                'logo_svg' => 'bank_logo_27.svg',
            ),
            array(
                'id' => '20',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'HABIB BANK LIMITED',
                'category' => 'Foreign Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_56.png',
                'logo_svg' => 'bank_logo_56.svg',
            ),
            array(
                'id' => '21',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'HONGKONG & SHANGHAI BANKING CORP.',
                'category' => NULL,
                'transaction_type' => NULL,
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_48.png',
                'logo_svg' => 'bank_logo_48.svg',
            ),
            array(
                'id' => '22',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'IFIC BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_15.png',
                'logo_svg' => 'bank_logo_15.svg',
            ),
            array(
                'id' => '23',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'ISLAMI BANK BANGLDESH LIMITED',
                'category' => NULL,
                'transaction_type' => NULL,
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_12.png',
                'logo_svg' => 'bank_logo_12.svg',
            ),
            array(
                'id' => '24',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'JAMUNA BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_32.png',
                'logo_svg' => 'bank_logo_32.svg',
            ),
            array(
                'id' => '25',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'JANATA BANK LIMITED',
                'category' => 'State-owned Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_5.png',
                'logo_svg' => 'bank_logo_5.svg',
            ),
            array(
                'id' => '26',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'MERCANTILE BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_19.png',
                'logo_svg' => 'bank_logo_19.svg',
            ),
            array(
                'id' => '27',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'MUTUAL TRUST BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_10.png',
                'logo_svg' => 'bank_logo_10.svg',
            ),
            array(
                'id' => '28',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'NATIONAL BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_16.png',
                'logo_svg' => 'bank_logo_16.svg',
            ),
            array(
                'id' => '29',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'NATIONAL BANK OF PAKISTAN',
                'category' => 'Foreign Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_54.png',
                'logo_svg' => 'bank_logo_54.svg',
            ),
            array(
                'id' => '30',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'NATIONAL CREDIT & COMMERCE BANK LIMITED',
                'category' => NULL,
                'transaction_type' => NULL,
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_18.png',
                'logo_svg' => 'bank_logo_18.svg',
            ),
            array(
                'id' => '31',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'ONE BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_25.png',
                'logo_svg' => 'bank_logo_25.svg',
            ),
            array(
                'id' => '32',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'PRIME BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_21.png',
                'logo_svg' => 'bank_logo_21.svg',
            ),
            array(
                'id' => '33',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'PUBALI BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_14.png',
                'logo_svg' => 'bank_logo_14.svg',
            ),
            array(
                'id' => '34',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'RAJSHAHI KRISHI UNNAYAN BANK',
                'category' => 'Specialized Development',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_40.png',
                'logo_svg' => 'bank_logo_40.svg',
            ),
            array(
                'id' => '35',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'RUPALI BANK LIMITED',
                'category' => 'State-owned Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_4.png',
                'logo_svg' => 'bank_logo_4.svg',
            ),
            array(
                'id' => '36',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'SHAHJALAL ISLAMI BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_33.png',
                'logo_svg' => 'bank_logo_33.svg',
            ),
            array(
                'id' => '37',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'SOCIAL ISLAMI BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_22.png',
                'logo_svg' => 'bank_logo_22.svg',
            ),
            array(
                'id' => '38',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'SONALI BANK LIMITED',
                'category' => 'State-owned Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_2.png',
                'logo_svg' => 'bank_logo_2.svg',
            ),
            array(
                'id' => '39',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'SOUTHEAST BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_20.png',
                'logo_svg' => 'bank_logo_20.svg',
            ),
            array(
                'id' => '40',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'STANDARD BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_23.png',
                'logo_svg' => 'bank_logo_23.svg',
            ),
            array(
                'id' => '41',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'STANDARD CHARTERED BANK',
                'category' => 'Foreign Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_49.png',
                'logo_svg' => 'bank_logo_49.svg',
            ),
            array(
                'id' => '42',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'STATE BANK OF INDIA',
                'category' => 'Foreign Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_51.png',
                'logo_svg' => 'bank_logo_51.svg',
            ),
            array(
                'id' => '43',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'THE CITY BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_17.png',
                'logo_svg' => 'bank_logo_17.svg',
            ),
            array(
                'id' => '44',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'ICB ISLAMIC BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_34.png',
                'logo_svg' => 'bank_logo_34.svg',
            ),
            array(
                'id' => '45',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'THE PREMIER BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_29.png',
                'logo_svg' => 'bank_logo_29.svg',
            ),
            array(
                'id' => '46',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'TRUST BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_31.png',
                'logo_svg' => 'bank_logo_31.svg',
            ),
            array(
                'id' => '47',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'UNITED COMMERCIAL BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_9.png',
                'logo_svg' => 'bank_logo_9.svg',
            ),
            array(
                'id' => '48',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'UTTARA BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_13.png',
                'logo_svg' => 'bank_logo_13.svg',
            ),
            array(
                'id' => '49',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'WOORI BANK',
                'category' => 'Foreign Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_52.png',
                'logo_svg' => 'bank_logo_52.svg',
            ),
            array(
                'id' => '50',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'NRB COMMERCIAL BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_63.png',
                'logo_svg' => 'bank_logo_63.svg',
            ),
            array(
                'id' => '51',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'UNION BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_67.png',
                'logo_svg' => 'bank_logo_67.svg',
            ),
            array(
                'id' => '52',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'SBAC BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_64.png',
                'logo_svg' => 'bank_logo_64.svg',
            ),
            array(
                'id' => '53',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'MEGHNA BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_59.png',
                'logo_svg' => 'bank_logo_59.svg',
            ),
            array(
                'id' => '54',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'THE FARMERS BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_66.png',
                'logo_svg' => 'bank_logo_66.svg',
            ),
            array(
                'id' => '55',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'MIDLAND BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_60.png',
                'logo_svg' => 'bank_logo_60.svg',
            ),
            array(
                'id' => '56',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'NRB BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_62.png',
                'logo_svg' => 'bank_logo_62.svg',
            ),
            array(
                'id' => '57',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'MODHUMOTI BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_61.png',
                'logo_svg' => 'bank_logo_61.svg',
            ),
            array(
                'id' => '58',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'NRB GLOBAL BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_64.png',
                'logo_svg' => 'bank_logo_64.svg',
            ),
            array(
                'id' => '59',
                'country_id' => '19',
                'beneficiary_type_id' => 1,
                'name' => 'SHIMANTO BANK LIMITED',
                'category' => 'Private Commercial',
                'transaction_type' => 'Account Deposit',
                'currency' => 'BDT',
                'bank_data' =>
                    array(),
                'enabled' => true,
                'logo_png' => 'bank_logo_65.png',
                'logo_svg' => 'bank_logo_65.svg',
            ),
        );
    }
}
